/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Health
     * @description Liveness probe used by Phase 1 manual verification.
     */
    get: operations["get_health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Customers
     * @description Search customers (look-alikes included).
     */
    get: operations["search_customers_api_read_customers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/customers/{customer_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Customer
     * @description One customer.
     */
    get: operations["get_customer_api_read_customers__customer_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Orders
     * @description Orders of one customer.
     */
    get: operations["list_orders_api_read_orders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/orders/{order_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Order
     * @description One order with items.
     */
    get: operations["get_order_api_read_orders__order_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/tickets/{ticket_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ticket
     * @description One ticket.
     */
    get: operations["get_ticket_api_read_tickets__ticket_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/replacements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Replacements
     * @description Replacements for one order item.
     */
    get: operations["list_replacements_api_read_replacements_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/refunds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Refunds
     * @description Refunds linked to one ticket.
     */
    get: operations["list_refunds_api_read_refunds_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/policies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Policies
     * @description All policy rules.
     */
    get: operations["list_policies_api_read_policies_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/read/probe/mutation/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Probe Mutation
     * @description Probe an idempotency key (found with identity, or not found).
     */
    get: operations["probe_mutation_api_read_probe_mutation__key__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/shop/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Orders
     * @description Customer orders, optionally filtered by customer code.
     */
    get: operations["list_orders_api_shop_orders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/shop/orders/{order_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Order
     * @description Order detail.
     */
    get: operations["get_order_api_shop_orders__order_code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/shop/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Ticket
     * @description Raise a ticket from the shop.
     */
    post: operations["create_ticket_api_shop_tickets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/shop/tickets/{ticket_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ticket
     * @description Ticket status for the customer.
     */
    get: operations["get_ticket_api_shop_tickets__ticket_code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Sandbox login: mint a session and set the cookie.
     */
    post: operations["login_api_ops_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Revoke the session and clear the cookie.
     */
    post: operations["logout_api_ops_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tickets
     * @description Paginated ticket queue.
     */
    get: operations["list_tickets_api_ops_tickets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/tickets/{ticket_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ticket
     * @description Ticket detail.
     */
    get: operations["get_ticket_api_ops_tickets__ticket_code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/ui-flags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Ui Flags
     * @description UI behavior switches armed via fault plans.
     */
    get: operations["get_ui_flags_api_ops_ui_flags_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search Customers
     * @description Customer search (look-alikes included).
     */
    get: operations["search_customers_api_ops_customers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/orders/{order_code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Order
     * @description Order detail with items.
     */
    get: operations["get_order_api_ops_orders__order_code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/replacements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Replacement
     * @description Commit a replacement (201) or replay it (200) for a known key.
     */
    post: operations["create_replacement_api_ops_replacements_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/refunds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Refund
     * @description Commit a refund (201) or replay it (200) for a known key.
     */
    post: operations["create_refund_api_ops_refunds_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/tickets/{ticket_code}/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Note
     * @description Attach an internal note (201) or replay it (200).
     */
    post: operations["create_note_api_ops_tickets__ticket_code__notes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/tickets/{ticket_code}/reply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Reply
     * @description Send a customer reply (201) or replay it (200).
     */
    post: operations["create_reply_api_ops_tickets__ticket_code__reply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ops/tickets/{ticket_code}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update Status
     * @description Change ticket status (201) or replay it (200).
     */
    post: operations["update_status_api_ops_tickets__ticket_code__status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CustomerRead
     * @description Customer as seen by read APIs and the shop.
     */
    CustomerRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Email */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       */
      status: string;
      /**
       * Service
       * @default northstar-worker-backend
       */
      service: string;
      /**
       * Version
       * @default 0.1.0-phase1
       */
      version: string;
    };
    /**
     * LoginRequest
     * @description Sandbox login (dummy credential accepted; real auth out of scope).
     */
    LoginRequest: {
      /** Agent Name */
      agent_name: string;
      /**
       * Password
       * @default
       */
      password: string;
    };
    /**
     * LoginResponse
     * @description Issued session (token also set as httponly cookie).
     */
    LoginResponse: {
      /** Agent Name */
      agent_name: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /**
     * LogoutResponse
     * @description Logout acknowledgement.
     */
    LogoutResponse: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * NoteCreate
     * @description Internal note (never customer-visible).
     */
    NoteCreate: {
      /**
       * Kind
       * @default internal
       */
      kind: string;
      /** Body */
      body: string;
      /**
       * Author
       * @default ops-agent
       */
      author: string;
    };
    /**
     * NoteRead
     * @description Ticket note row.
     */
    NoteRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Ticket Id
       * Format: uuid
       */
      ticket_id: string;
      /** Kind */
      kind: string;
      /** Body */
      body: string;
      /** Author */
      author: string;
      /** Mutation Key */
      mutation_key: string | null;
    };
    /**
     * OrderItemRead
     * @description One order line.
     */
    OrderItemRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Sku */
      sku: string;
      /** Title */
      title: string;
      /** Qty */
      qty: number;
      /** Unit Paise */
      unit_paise: number;
      /** Category */
      category: string;
    };
    /**
     * OrderRead
     * @description Order with its items.
     */
    OrderRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /**
       * Customer Id
       * Format: uuid
       */
      customer_id: string;
      /** Status */
      status: string;
      /** Total Paise */
      total_paise: number;
      /** Paid Paise */
      paid_paise: number;
      /**
       * Placed At
       * Format: date-time
       */
      placed_at: string;
      /** Delivered At */
      delivered_at: string | null;
      /**
       * Items
       * @default []
       */
      items: components["schemas"]["OrderItemRead"][];
    };
    /**
     * PolicyRead
     * @description Versioned policy rule with its params.
     */
    PolicyRead: {
      /** Rule Key */
      rule_key: string;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      /** Version */
      version: number;
    };
    /**
     * ProbeResult
     * @description Mutation probe: found + identity when present, never an error.
     */
    ProbeResult: {
      /** Found */
      found: boolean;
      /** Kind */
      kind?: string | null;
      /** Entity Id */
      entity_id?: string | null;
    };
    /**
     * RefundCreate
     * @description Refund request in integer paise.
     */
    RefundCreate: {
      /** Order Code */
      order_code: string;
      /** Ticket Code */
      ticket_code: string;
      /** Amount Paise */
      amount_paise: number;
    };
    /**
     * RefundRead
     * @description Refund row.
     */
    RefundRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Order Id
       * Format: uuid
       */
      order_id: string;
      /**
       * Customer Id
       * Format: uuid
       */
      customer_id: string;
      /**
       * Ticket Id
       * Format: uuid
       */
      ticket_id: string;
      /** Amount Paise */
      amount_paise: number;
      /** Status */
      status: string;
      /** Mutation Key */
      mutation_key: string;
    };
    /**
     * ReplacementCreate
     * @description Replacement request, addressed by human codes (UI-friendly).
     */
    ReplacementCreate: {
      /** Order Code */
      order_code: string;
      /** Item Sku */
      item_sku: string;
      /** Ticket Code */
      ticket_code: string;
      /** Reason */
      reason?: string | null;
    };
    /**
     * ReplacementRead
     * @description Replacement row.
     */
    ReplacementRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Order Id
       * Format: uuid
       */
      order_id: string;
      /**
       * Order Item Id
       * Format: uuid
       */
      order_item_id: string;
      /**
       * Customer Id
       * Format: uuid
       */
      customer_id: string;
      /**
       * Ticket Id
       * Format: uuid
       */
      ticket_id: string;
      /** Status */
      status: string;
      /** Mutation Key */
      mutation_key: string;
    };
    /**
     * ReplyCreate
     * @description Customer-visible reply (stored as a customer_reply note).
     */
    ReplyCreate: {
      /** Body */
      body: string;
    };
    /**
     * ShopTicketCreate
     * @description Raise-ticket form: customer-identified, optionally order-linked.
     */
    ShopTicketCreate: {
      /** Customer Code */
      customer_code: string;
      /** Order Code */
      order_code?: string | null;
      /** Subject */
      subject: string;
      /** Body */
      body: string;
      /**
       * Category
       * @default general
       */
      category: string;
    };
    /**
     * StatusUpdate
     * @description Ticket status transition.
     */
    StatusUpdate: {
      /** To Status */
      to_status: string;
    };
    /**
     * TicketListResponse
     * @description Paginated ticket queue (the worker must paginate).
     */
    TicketListResponse: {
      /** Items */
      items: components["schemas"]["TicketRead"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /**
     * TicketRead
     * @description Support ticket.
     */
    TicketRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Code */
      code: string;
      /**
       * Customer Id
       * Format: uuid
       */
      customer_id: string;
      /** Order Id */
      order_id: string | null;
      /** Subject */
      subject: string;
      /** Body */
      body: string;
      /** Category */
      category: string;
      /** Status */
      status: string;
      /** Version */
      version: number;
    };
    /**
     * UiFlags
     * @description `/ops` behavior switches armed via fault plans (Phase 9 owns faults).
     */
    UiFlags: {
      /**
       * Removed Search Field
       * @default false
       */
      removed_search_field: boolean;
      /**
       * Dom Drift
       * @default false
       */
      dom_drift: boolean;
      /**
       * Stale Rerender
       * @default false
       */
      stale_rerender: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  search_customers_api_read_customers_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_customer_api_read_customers__customer_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        customer_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_orders_api_read_orders_get: {
    parameters: {
      query: {
        customer_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_order_api_read_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ticket_api_read_tickets__ticket_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_replacements_api_read_replacements_get: {
    parameters: {
      query: {
        order_item_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReplacementRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_refunds_api_read_refunds_get: {
    parameters: {
      query: {
        ticket_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefundRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_policies_api_read_policies_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicyRead"][];
        };
      };
    };
  };
  probe_mutation_api_read_probe_mutation__key__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProbeResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_orders_api_shop_orders_get: {
    parameters: {
      query?: {
        customer_code?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_order_api_shop_orders__order_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_ticket_api_shop_tickets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShopTicketCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ticket_api_shop_tickets__ticket_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_ops_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_ops_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tickets_api_ops_tickets_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ticket_api_ops_tickets__ticket_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ticket_code: string;
      };
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_ui_flags_api_ops_ui_flags_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UiFlags"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_customers_api_ops_customers_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_order_api_ops_orders__order_code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_code: string;
      };
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_replacement_api_ops_replacements_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplacementCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReplacementRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_refund_api_ops_refunds_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefundCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefundRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_note_api_ops_tickets__ticket_code__notes_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        ticket_code: string;
      };
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoteCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_reply_api_ops_tickets__ticket_code__reply_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        ticket_code: string;
      };
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_status_api_ops_tickets__ticket_code__status_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path: {
        ticket_code: string;
      };
      cookie?: {
        ops_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TicketRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
